[string]$TFSCollection="http://dtraflon2k107:8080/tfs/puma"
[String]$TeamProjectBranch="$/ePuma/NAV/Dev"
[String]$LocalWrkSpcMapFldr="C:\Puma"
[String]$workSpaceName="ePuma_workspace"
[String]$NowSyncScript="C:\Puma\ePuma\NAV\Dev\PowerShell\Scripts\NowSync.ps1"
[string]$TfPath="C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE"